# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 947b633f277a2cbab67fb43a457628583b8b4c7fc5305c478abdcb2fe43a7f5b17e11961fafdeb7b0ad84c526a69b4fcad8a5bf059d0b0d4e0bf055a6849c543

test:
  secret_key_base: 46c4c8b68b0ac7243ea3ed134e27c7c5f1bb79f45bdc151b3aba35faa8efbfd347ecca2200a25d77ca189edb62607c3aef3b636cfc6a1c6cf466bb720a9f912a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
